home/urls.py
from django.urls import path

from home.views import HomeTemplateView

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home')
]

onlinestore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('category/', include('category.urls')),
    path('', include('home.urls')),
    path('user/', include('user.urls')),
    path('', include('django.contrib.auth.urls')),
    path('api/',include('rest_framework.urls'))
]

product/urls.py
from django.urls import path, include

from product.views import ProductCreateView, ProductListView, ProductUpdateView, ProductDeleteView, ProductDetailView
from rest_framework import routers
from product.views import ProductViewSet

router = routers.DefaultRouter()
router.register(r'', ProductViewSet)

urlpatterns = [
    path('product-create/', ProductCreateView.as_view(), name='product-create'),
    path('product-list/', ProductListView.as_view(), name='list_of_products'),
    path('product-update/<int:pk>/', ProductUpdateView.as_view(), name='product-update'),
    path('product-delete/<int:pk>', ProductDeleteView.as_view(), name='product-delete'),
    path('product-details/<int:pk>', ProductDetailView.as_view(), name='product-details'),
    path('api/', include(router.urls)),
]

product/models.py
from django.db import models


class Product(models.Model):
    product_name = models.CharField(max_length=30)
    description = models.CharField(max_length=30)
    price = models.IntegerField()
    category = models.ForeignKey('category.Category', on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.product_name

product/forms.py
from django import forms
from django.forms import TextInput, HiddenInput

from product.models import Product


class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        widgets = {
            'product_name': TextInput(attrs={
                'placeholder': 'Please insert category name.',
                'class': 'input is-primary'
            }),
            'description': TextInput(attrs={
                'placeholder': 'Please insert a description.',
                'class': 'input is-primary'
            }),
            'price': TextInput(attrs={
                'placeholder': 'Please insert a price.',
                'class': 'input is-primary'
            })
        }

    def __init__(self, *args, **kwargs):
        super(ProductCreateForm, self).__init__(*args, **kwargs)
        self.fields['product_name'].required = True
        self.fields['description'].required = True
        self.fields['price'].required = True



    def clean(self):
        cleaned_data = self.cleaned_data
        name = cleaned_data.get('product_name')
        description = cleaned_data.get('description')
        all_products = Product.objects.all()
        for product in all_products:
            if str(name) == str(product.product_name):
                msg = 'This product is already saved in Database.'
                self._errors['product_name'] = self.error_class([msg])
            if str(description) == str(product.description):
                msg2 = 'This description is already saved in Database.'
                self._errors['description'] = self.error_class([msg2])
        return cleaned_data

product/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from product.serializers import ProductSerializer
from product.forms import ProductCreateForm
from product.models import Product
from rest_framework import viewsets

class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = 'product/product_create.html'
    model = Product
    # fields = '__all__'
    # fields = [
    #     'product_name',
    #     'description',
    #     'price'
    # ]
    form_class = ProductCreateForm
    success_url = reverse_lazy('product-list')
    permission_required = 'product.change_product'


class ProductListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    template_name = 'product/product_list.html'
    model = Product
    context_object_name = 'all_products'
    permission_required = 'product.view_product'


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin,UpdateView):
    template_name = 'product/product_update.html'
    model = Product
    fields = '__all__'
    success_url = reverse_lazy('product-list')
    permission_required = 'product.update_product'

class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    template_name = 'product/product_delete.html'
    model = Product
    success_url = reverse_lazy('product-list')
    permission_required = 'product.delete_product'


class ProductDetailView(LoginRequiredMixin, PermissionRequiredMixin,DetailView):
    template_name = 'product/product_details.html'
    model = Product
    context_object_name = 'product_details'
    permission_required = 'product.details_product'


class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

templates/product/product_create.html
{% extends 'base.html' %}

{% block title %} Product Create {% endblock %}

{% block content %}

    <form method="post" action="">
        {% csrf_token %}
        {# {{ form.as_p }} #}

        {% for field in form %}
            <div class="field">
                <label class="label"> {{ field.label }}</label>     {# ne afiseaza denumirea campului #}
                <div class="control">
                    {{ field }}   {# aduce inoutul pt fiecare field #}
                </div>
                <span class="color_red">
                {{ field.errors }}    {# ne afiseaza erorile #}
            </span>
            </div>
        {% endfor %}


        <button type="submit">Save a new product</button>
        </br>
        <a href="{% url 'product-list' %}">Go back to product list</a>
    </form>

{% endblock %}

templates/product/product_delete.html
{% extends 'base.html' %}

{% block title %} Delete Product {% endblock %}

{% block content %}
    <form method="post">
    <h3>Are you sure you want to delete this product?</h3>
    {% csrf_token %}
    <button type="submit">YES</button>
    <a href={% url 'product-list' %}>NO</a>"
    </form>
{% endblock %}

templates/product/product_details.html
{% extends 'base.html' %}

{% block title %} Details Product {% endblock %}

{% block content %}


<section class="section">
         <div class="container">
            <div class="card">
              <div class="card-content">
                <div class="media">
                  <div class="media-left">
                    <figure class="image is-48x48">
                      <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
                    </figure>
                  </div>
                  <div class="media-content">
                    <p class="title is-4">{{ product_details.product_name }}</p>
                    <p class="subtitle is-6">{{product_details.category}}</p>
                    <p class="subtitle is-6">{{product_details.price}}</p>
                  </div>
                </div>

                <div class="content">
                    <h5>{{ product_details.product_description }} </h5>
                  <br>
                    <a href="{% url 'product-list' %}">Go to product list</a>
                </div>
              </div>
            </div>

         </div>
</section>

{% endblock %}

templates/product/product_list.html
{%  extends 'base.html' %}

{% block title %} Product List {% endblock %}

{% block content %}


<section class="section">
         <div class="container">
         <h1>{{ request.user.groups.get.name}}</h1>
              <table class="table">
                     <thead>
                     <tr>
                         <th>Product Name</th>
                         <th>Category Name</th>
                         <th>Description</th>
                         <th>Price</th>
                         <th>Actions</th>
                     </tr>
                     </thead>
                    <tbody>
                    {% for product in all_products %}
                        <tr>
                            <td>{{ product.product_name }}</td>
                            <td>{{ product.category }}</td>
                            <td>{{ product.description }}</td>
                            <td>{{ product.price }}</td>
                            <td>
                                {% if perms.product.change_product %}
                                <a href={% url 'product-update' product.id %}>Update</a>
                                {% endif %}
                            {% if perms.product.delete_product %}
                                <a href={% url 'product-delete' product.id %}>Delete</a>
                            {% endif %}
                            {% if perms.product.view_product %}
                                <a href={% url 'product-details' product.id %}>Details</a>
                            {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
              </table>
         {% if perms.product.add_product %}
             <a href={% url 'product-create' %}>Add new product</a>
         {% endif %}
         </div>
</section>
{% endblock %}>

templates/product/product_update.html
{% extends 'base.html' %}
{% block title %} Product update {% endblock %}
{% block content %}
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update details about this product</button>
    </form>
{% endblock %}